### ISSUE TITLE
intermittent "Expected BEGIN_OBJECT but was STRING at line 1 column 1 path" handling issue in papermc 1.20.6

### ISSUE THREAD

**Issue by foxunfocused** [Jakkoble/TwitchWhitelist#8]
[WARN] Unexpected exception while parsing console command "whitelist add potatotest"
[10.06 00:39:03] [Server] org.bukkit.command.CommandExceptionUnhandled exception executing command 'whitelist' in plugin TwitchWhitelist v2.2
[10.06 00:39:03] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
[10.06 00:39:03] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
[10.06 00:39:03] [Server] 	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:964) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:949) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
[10.06 00:39:03] [Server] 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10.06 00:39:03] [Server] Caused bycom.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[10.06 00:39:03] [Server] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at TwitchWhitelist-2.2.jar/de.jakkoble.WhitelistKt.getRequest(Whitelist.kt:57) ~[TwitchWhitelist-2.2.jar:?]
[10.06 00:39:03] [Server] 	at TwitchWhitelist-2.2.jar/de.jakkoble.WhitelistKt.getUserDataFromName(Whitelist.kt:46) ~[TwitchWhitelist-2.2.jar:?]
[10.06 00:39:03] [Server] 	at TwitchWhitelist-2.2.jar/de.jakkoble.WhitelistCommand.onCommand(WhitelistCommand.kt:76) ~[TwitchWhitelist-2.2.jar:?]
[10.06 00:39:03] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
[10.06 00:39:03] [Server] 	... more
[10.06 00:39:03] [Server] Caused byjava.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[10.06 00:39:03] [Server] 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
[10.06 00:39:03] [Server] 	at TwitchWhitelist-2.2.jar/de.jakkoble.WhitelistKt.getRequest(Whitelist.kt:57) ~[TwitchWhitelist-2.2.jar:?]
[10.06 00:39:03] [Server] 	at TwitchWhitelist-2.2.jar/de.jakkoble.WhitelistKt.getUserDataFromName(Whitelist.kt:46) ~[TwitchWhitelist-2.2.jar:?]
[10.06 00:39:03] [Server] 	at TwitchWhitelist-2.2.jar/de.jakkoble.WhitelistCommand.onCommand(WhitelistCommand.kt:76) ~[TwitchWhitelist-2.2.jar:?]
[10.06 00:39:03] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
[10.06 00:39:03] [Server] 	... more

**Comment by Jakkoble** [comment]
Hey there,
sorry for the late response. I will have a look on your issue tomorrow.
Dears, Jakob.

**Comment by foxunfocused** [comment]
Stopped seeing this in Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z)
This may have just been a Paper issue with a code reversion https://github.com/PaperMC/Paper/pull/10896

**Comment by Jakkoble** [comment]
Oh, well this seems like the problem.
The plugin works just fine in the newest Paper version 1.20.6-147. Thanks for your research!

**Comment by foxunfocused** [comment]
I may have spoken too soon.  Manual entry is no longer doing it, but Twitch Redeems are still randomly erroring out.  It may be a similar issue

**Comment by Jakkoble** [comment]
Have you tried out the new plugin release [v2.3](https://github.com/Jakkoble/TwitchWhitelist/releases/tag/v2.3) with the newest [PaperMC 1.20.6 Build](https://api.papermc.io/v2/projects/paper/versions/1.20.6/builds/147/downloads/paper-1.20.6-147.jar)? This combination works just fine for me.

**Comment by foxunfocused** [comment]
I missed the v2.3 update coming out! I'll toss it into the server files and let it update during our nightly restart.

**Comment by foxunfocused** [comment]
Sorry for the delay. I had a big move and didn't have internet for a few days.  No issues anymore! Thanks for reopening this!

**Comment by ArtemBay** [comment]
I got same error too. Papermc 1.21 build 123. Error says `Expected BEGIN_OBJECT but was STRING at line 1 column 3 path`. My config on scrennshot
![image](https://github.com/user-attachments/assets/0b2853b9-ddf6-4e9d-aea4-3ff8170e1d8e)
